version: '3.8'
services:
  portfolio:
    container_name: portfolio
    image: portfolio
    build:
      context: .
      target: test
    volumes:
      - ./src:/app/src
    ports:
        - "4200:80"